### ISSUE TITLE
KeyError when using wrong token

### ISSUE THREAD

**Issue by benzolius** [JamesGardiner/chwrapper#14]
I get "KeyError: 'x-ratelimit-reset'" in the traceback, when trying wrong token.
I have a small fix for this problem by which I get a better error message.

**Comment by JamesGardiner** [comment]
Thanks for raising the issue @benzolius. Feel free to submit a PR when you get a chance.

**Comment by benzolius** [comment]
I have a PR, please merge it if is ok.

BTW thanks for this awesome package, I'll use it for our application and I hope we can contribute more.

Best Regards
