### ISSUE TITLE
Rate Limiter implementation hides the error

### ISSUE THREAD

**Issue by antdking** [JamesGardiner/chwrapper#23]
Going through the codebase before we begin using this library, I've noticed that the `rate_limit` decorator will do one of 2 things.
* cause unexpected hangs
* do nothing at all

This depends on whether `X-Ratelimit-Remain` will be set to `'0'` before a 429 response is returned. (error statuses will be raised by `handle_http_error`). This is undocumented behaviour in the API.

I recommend not having the decorator at all, as causing software to hang is not a good idea.
The headers are also undocumented, and there are [reports](http://forum.aws.chdev.org/t/rate-limit-header-naming-issue/245) on the forum of them changing the naming (though that was last year).

**Comment by JamesGardiner** [comment]
Hi @cybojenix - thanks for considering the use of this library.

Would your approach use a custom exception handler when a `429` error is returned? I use the rate_limit decorator a lot, but can see your points: i. That the headers are undocumented and may change over time as the beta is formalised and ii. That it restricts how users may want to handle the `429` status.

I have a number of constraints to follow for this library, one of which is obeying rate limits set by Companies House. Bearing that in mind, would the following solution be flexible enough for your use case?

    - Implement a standard `429` exception handler that obeys rate limits and resumes execution at the correct time
    - Allow that exception handler to be overridden at the instance level for user specified exception handling

**Comment by antdking** [comment]
I would actually leave it unhandled. I assume that since the rate limiter works, the header reaches 0 before a 429 is given.

If you document `Service.session` as being an instance of `request.Session`, then the user can then do something along the lines of this to handle your rate limiting.

```python
class RateLimiterHTTPAdapter(requests.adapters.HTTPAdapter):
    def build_response(req, resp):
        # your code for handling the ratelimiter

service.session.mount('https://', RateLimiterHTTPAdapter())
```

using this interface means that others can use `session` in a similar way but for other purposes.
