### ISSUE TITLE
How to return more than 20 items.

### ISSUE THREAD

**Issue by tjearl** [JamesGardiner/chwrapper#31]
Hi James,

This is more of a question than an issue (I'm very much a beginner when it comes to working with Python). 

How would I go about getting your wrapper to return more than 20 items at a time when performing a search?

The JSON objects returned by the following:

`search = 'Random Company'
response = search_client.search_companies(search)
r = json.loads(response.text)`

only include the first 20 items of the search:

`'items_per_page': 20,
 'kind': 'search#companies',
 'page_number': 1,
 'start_index': 0,
 'total_results': 154886}`

How would I go about getting to the other pages/increasing the number of items per page?

Sorry if this isn't the right place to post questions of this kind...

**Comment by JamesGardiner** [comment]
Apologies @tjearl - I didn't catch this issue being opened. Pass any keyword arguments as the last arguments in the search method. For instance:

```Python
response = search_client.search_companies('Company name', page_number=2)
```
